name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7.x"
          - "3.8.x"
          - "3.9.x"
          - "3.10.x"

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: actions/setup-python@v4.2.0
        with:
          python-version: "${{ matrix.python-version }}"

      - run: make dependencies

      - run: make runtests
