name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "2.7.x"
          - "3.6.x"

    steps:
      - uses: actions/checkout@v2.3.5

      - uses: actions/setup-python@v2.2.2
        with:
          python-version: "${{ matrix.python-version }}"

      - run: make dependencies

      - run: make runtests
